
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Roll(props) {
  const { nodes, materials } = useGLTF('/ferrari_laferrari__www.vecarz.com.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.582, 0, -3.14]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-1.582, 0.002, 0]} scale={0.599}>
            <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
              <group
                position={[0.248, -3.485, 0]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
                scale={5.308}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_115.geometry}
                  material={materials['Material.144']}
                  position={[-24.41, 40.976, 11.037]}
                  rotation={[0, 0, -Math.PI]}
                  scale={0.998}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_118.geometry}
                  material={materials['Material.145']}
                  position={[-24.41, -38.202, 10.567]}
                  rotation={[0, 0, -Math.PI]}
                  scale={0.998}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_121.geometry}
                  material={materials['Material.146']}
                  position={[24.556, -38.202, 10.567]}
                  scale={0.998}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_124.geometry}
                  material={materials['Material.147']}
                  position={[24.556, 40.935, 10.995]}
                  scale={0.998}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials.black}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials.Carbon_fiber}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials.Body}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials.Disk}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials.break_lights_glasses}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials.Logos}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials.wireframe_color_0xE0C657}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.wireframe_color_0xE05656}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials.wireframe_color_0x57E0C6}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials.Viper}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials.breake_lights_chrom}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials.breake_chrome_2}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={materials.Under}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials.under_carreage}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={materials.Rear_logo}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={materials['head_lights_glasses.002']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={materials.red_light}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials.rear_black_something}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={materials.wireframe_color_0xE056560}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={materials.Rear_headlights}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_48.geometry}
                  material={materials.chrome}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_50.geometry}
                  material={materials.wireframe_color_0x8606062}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_52.geometry}
                  material={materials.wireframe_color_0xE0C6571}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_54.geometry}
                  material={materials.wireframe_color_0xE5A6D7}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_56.geometry}
                  material={materials.Engine_glass}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_58.geometry}
                  material={materials.Glasses}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_60.geometry}
                  material={materials['Material.019']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_62.geometry}
                  material={materials['break_lights.001']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_64.geometry}
                  material={materials.run_lights}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_66.geometry}
                  material={materials.tail_lights}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_68.geometry}
                  material={materials.wireframe_color_0x1C59B11}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_70.geometry}
                  material={materials.wireframe_color_0xB11C95}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_72.geometry}
                  material={materials.Rear_something}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_74.geometry}
                  material={materials.black_2}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_76.geometry}
                  material={materials['black.007']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_78.geometry}
                  material={materials['black.005']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_80.geometry}
                  material={materials['Front_headlights.001']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_82.geometry}
                  material={materials.wireframe_color_0x1C59B13}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_84.geometry}
                  material={materials.chrome0}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_86.geometry}
                  material={materials.hood_black}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_88.geometry}
                  material={materials.Inside_stickers}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_90.geometry}
                  material={materials['Material.009']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_92.geometry}
                  material={materials['Interior_2.001']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_94.geometry}
                  material={materials.int_mirror}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_96.geometry}
                  material={materials.wireframe_color_0x1C59B14}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_98.geometry}
                  material={materials.side_mirrors}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_100.geometry}
                  material={materials.Seets_logo}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_102.geometry}
                  material={materials.seats_nuts}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_104.geometry}
                  material={materials.seat_belt_lock}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_106.geometry}
                  material={materials.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_108.geometry}
                  material={materials.wireframe_color_0x8606063}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_110.geometry}
                  material={materials.wireframe_color_0xE056562}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_112.geometry}
                  material={materials.sreerean_wheel_buttons}
                />
              </group>
              <group
                position={[134.205, 52.215, -202.703]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={5.666}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_127.geometry}
                  material={materials['tread.001']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_129.geometry}
                  material={materials['disc.003']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_131.geometry}
                  material={materials['visse.009']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_133.geometry}
                  material={materials['Material.111']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_135.geometry}
                  material={materials['rim.001']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_137.geometry}
                  material={materials['Material.112']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_139.geometry}
                  material={materials['Material.113']}
                />
              </group>
              <group
                position={[-134.552, 52.215, -202.703]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={5.666}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_142.geometry}
                  material={materials['tread.002']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_144.geometry}
                  material={materials['disc.004']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_146.geometry}
                  material={materials['visse.011']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_148.geometry}
                  material={materials['Material.114']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_150.geometry}
                  material={materials['rim.002']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_152.geometry}
                  material={materials['Material.115']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_154.geometry}
                  material={materials['Material.116']}
                />
              </group>
              <group
                position={[133.208, 54.662, 217.374]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={5.975}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_157.geometry}
                  material={materials['tread.003']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_159.geometry}
                  material={materials['disc.005']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_161.geometry}
                  material={materials['visse.012']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_163.geometry}
                  material={materials['Material.117']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_165.geometry}
                  material={materials['rim.003']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_167.geometry}
                  material={materials['Material.118']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_169.geometry}
                  material={materials['Material.119']}
                />
              </group>
              <group
                position={[-133.556, 54.662, 217.374]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={5.975}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_172.geometry}
                  material={materials['tread.004']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_174.geometry}
                  material={materials['disc.006']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_176.geometry}
                  material={materials['visse.013']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_178.geometry}
                  material={materials['Material.120']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_180.geometry}
                  material={materials['rim.004']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_182.geometry}
                  material={materials['Material.121']}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_184.geometry}
                  material={materials['Material.122']}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ferrari_laferrari__www.vecarz.com.glb')